### ISSUE TITLE
Please make it compatible with new version of Brackets 1.11

### ISSUE THREAD

**Issue by irfandayan** [DH3ALEJANDRO/brackets-open-in-browser#28] opened 2018-01-19 10:31 UTC
Open in browser is not working with new version of Brackets 1.11. Please make it work with new version of Brackets 1.11.

Open in browser button does not show up for Brackets 1.11?

it is an awesome extension, and i think, you must keep it up to date and that would really appreciable. Thanks

**Comment by irfandayan** [comment] 2018-01-27 13:18
I would really appreciate, if you could update about this fix? Thanks

**Comment by DH3ALEJANDRO** [comment] 2018-01-30 14:33
Duplicate of #27

**Closed by DH3ALEJANDRO** 2018-01-30 14:33 UTC
